// Generated by gencpp from file msgs/People.msg
// DO NOT EDIT!


#ifndef MSGS_MESSAGE_PEOPLE_H
#define MSGS_MESSAGE_PEOPLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <msgs/Person.h>

namespace msgs
{
template <class ContainerAllocator>
struct People_
{
  typedef People_<ContainerAllocator> Type;

  People_()
    : header()
    , people()  {
    }
  People_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , people(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::msgs::Person_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msgs::Person_<ContainerAllocator> >> _people_type;
  _people_type people;





  typedef boost::shared_ptr< ::msgs::People_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs::People_<ContainerAllocator> const> ConstPtr;

}; // struct People_

typedef ::msgs::People_<std::allocator<void> > People;

typedef boost::shared_ptr< ::msgs::People > PeoplePtr;
typedef boost::shared_ptr< ::msgs::People const> PeopleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs::People_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs::People_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs::People_<ContainerAllocator1> & lhs, const ::msgs::People_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.people == rhs.people;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs::People_<ContainerAllocator1> & lhs, const ::msgs::People_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msgs::People_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs::People_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs::People_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs::People_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs::People_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs::People_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs::People_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95b48de870826c96ff3a6c908f73255b";
  }

  static const char* value(const ::msgs::People_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95b48de870826c96ULL;
  static const uint64_t static_value2 = 0xff3a6c908f73255bULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs::People_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs/People";
  }

  static const char* value(const ::msgs::People_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs::People_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Person[] people\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: msgs/Person\n"
"string              name\n"
"geometry_msgs/Pose  pose\n"
"geometry_msgs/Point velocity\n"
"float64             reliability\n"
"string[]            tagnames\n"
"string[]            tags\n"
"Proxemic            proxemic\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: msgs/Proxemic\n"
"# shift of the center of the proxemics (shift of Gauss)\n"
"geometry_msgs/Point centerShift\n"
"# spread of \n"
"geometry_msgs/Point spread\n"
"# rotation of proxemics (rotation of Gauss)\n"
"float64 rotation\n"
"# min cost to get in costmaps\n"
"int64 freeBorder\n"
"# max cost that does not count as lethal obstacle\n"
"int64 lethalBorder\n"
;
  }

  static const char* value(const ::msgs::People_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs::People_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.people);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct People_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs::People_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs::People_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "people[]" << std::endl;
    for (size_t i = 0; i < v.people.size(); ++i)
    {
      s << indent << "  people[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msgs::Person_<ContainerAllocator> >::stream(s, indent + "    ", v.people[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_MESSAGE_PEOPLE_H
