// Generated by gencpp from file msgs/Person.msg
// DO NOT EDIT!


#ifndef MSGS_MESSAGE_PERSON_H
#define MSGS_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Point.h>
#include <msgs/Proxemic.h>

namespace msgs
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : name()
    , pose()
    , velocity()
    , reliability(0.0)
    , tagnames()
    , tags()
    , proxemic()  {
    }
  Person_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , pose(_alloc)
    , velocity(_alloc)
    , reliability(0.0)
    , tagnames(_alloc)
    , tags(_alloc)
    , proxemic(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef double _reliability_type;
  _reliability_type reliability;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _tagnames_type;
  _tagnames_type tagnames;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _tags_type;
  _tags_type tags;

   typedef  ::msgs::Proxemic_<ContainerAllocator>  _proxemic_type;
  _proxemic_type proxemic;





  typedef boost::shared_ptr< ::msgs::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::msgs::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::msgs::Person > PersonPtr;
typedef boost::shared_ptr< ::msgs::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs::Person_<ContainerAllocator1> & lhs, const ::msgs::Person_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.pose == rhs.pose &&
    lhs.velocity == rhs.velocity &&
    lhs.reliability == rhs.reliability &&
    lhs.tagnames == rhs.tagnames &&
    lhs.tags == rhs.tags &&
    lhs.proxemic == rhs.proxemic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs::Person_<ContainerAllocator1> & lhs, const ::msgs::Person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msgs::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf3f030e63b6c82a38e38bd3144e2e45";
  }

  static const char* value(const ::msgs::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf3f030e63b6c82aULL;
  static const uint64_t static_value2 = 0x38e38bd3144e2e45ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs/Person";
  }

  static const char* value(const ::msgs::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string              name\n"
"geometry_msgs/Pose  pose\n"
"geometry_msgs/Point velocity\n"
"float64             reliability\n"
"string[]            tagnames\n"
"string[]            tags\n"
"Proxemic            proxemic\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: msgs/Proxemic\n"
"# shift of the center of the proxemics (shift of Gauss)\n"
"geometry_msgs/Point centerShift\n"
"# spread of \n"
"geometry_msgs/Point spread\n"
"# rotation of proxemics (rotation of Gauss)\n"
"float64 rotation\n"
"# min cost to get in costmaps\n"
"int64 freeBorder\n"
"# max cost that does not count as lethal obstacle\n"
"int64 lethalBorder\n"
;
  }

  static const char* value(const ::msgs::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.pose);
      stream.next(m.velocity);
      stream.next(m.reliability);
      stream.next(m.tagnames);
      stream.next(m.tags);
      stream.next(m.proxemic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs::Person_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "reliability: ";
    Printer<double>::stream(s, indent + "  ", v.reliability);
    s << indent << "tagnames[]" << std::endl;
    for (size_t i = 0; i < v.tagnames.size(); ++i)
    {
      s << indent << "  tagnames[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tagnames[i]);
    }
    s << indent << "tags[]" << std::endl;
    for (size_t i = 0; i < v.tags.size(); ++i)
    {
      s << indent << "  tags[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tags[i]);
    }
    s << indent << "proxemic: ";
    s << std::endl;
    Printer< ::msgs::Proxemic_<ContainerAllocator> >::stream(s, indent + "  ", v.proxemic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_MESSAGE_PERSON_H
